name: Release

on:
  # manual
  workflow_dispatch:
    inputs:
      source:
        default: 'feat/opensearch'
        type: string
        description: 'branch source'
        required: true
      version:
        type: string
        description: 'release version (ex: 11.1.8.1). By default maven version.'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.source }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build
        run: mvn clean package -DskipTests
      - name: Set version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ env.VERSION }}"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.VERSION }}"
          files: target/components/packages/*.zip
